name: etoiles_manager
description: Étoiles Manager - Gérez vos cotisations en toute simplicité | Les Étoiles de Horè-Koubi - Guinée Conakry
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  path: ^1.9.0
  pdf: ^3.10.0
  printing: ^5.11.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/

# Configuration de l'icône de l'application
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo_corrigé.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo_corrigé.png"

